### ISSUE TITLE
Custom command crashes on Nexus 9 Nougat

### ISSUE THREAD

**Issue by thyrlian** [offensive-security/kali-nethunter#1001]
### Device:
Nexus 9

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat 7.1.1 (Build number: N9F27L) the latest patch by far

### Built from repo (date and build command) or downloaded from website (links):
Built from repo (from yesterday, commit SHA1: `aff3e06d2aa5a129d51f3f3c4f120b1a9fac7c0f`), so that it supports Nougat.
Version: 3.15.4 - Built by Kali at 2017-02-13 11:50:21 PM GMT+01:00
[Build steps and commands](https://gist.github.com/thyrlian/3955ec313d3eada992a5cd656ad2de53) which I tried.

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Logs from Android Studio: (can't find file at `/tmp/recovery.log`)
```
09-24 11:43:01.776 5207-5207/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.offsec.nhterm, PID: 5207
                                                 java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/Term-nh.apk"],nativeLibraryDirectories=[/data/app-lib/Term-nh, /data/app/Term-nh.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libjackpal-termexec2.so"
                                                     at java.lang.Runtime.loadLibrary0(Runtime.java:984)
                                                     at java.lang.System.loadLibrary(System.java:1530)
                                                     at com.offsec.nhterm.TermExec.<clinit>(Unknown Source)
                                                     at com.offsec.nhterm.TermExec.a(Unknown Source)
                                                     at com.offsec.nhterm.e.a(Unknown Source)
                                                     at com.offsec.nhterm.e.f(Unknown Source)
                                                     at com.offsec.nhterm.e.<init>(Unknown Source)
                                                     at com.offsec.nhterm.Term.a(Unknown Source)
                                                     at com.offsec.nhterm.RemoteInterface.a(Unknown Source)
                                                     at com.offsec.nhterm.RunScriptNetHunter.b(Unknown Source)
                                                     at com.offsec.nhterm.RemoteInterface$1.onServiceConnected(Unknown Source)
                                                     at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1453)
                                                     at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1481)
                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
09-24 11:43:01.777 602-2419/? W/ActivityManager:   Force finishing activity com.offsec.nhterm/.RunScriptNetHunter
```

## Issue:
NetHunter app can be launched without any problem.  But
* Custom Commands will crash (any of them);
* Kali Chroot Manager -> Add Metapackages will crash (any of them);
* NetHunter Terminal will crash;
* USB Keyboard will crash;

Additional Info:
* NetHunter says Busybox Version: v1.25.0-NetHunter, and I've also tried to install the latest BusyBox Pro from Play Store (v1.27.2);
* Found a similar ticket [here](https://github.com/offensive-security/kali-nethunter/issues/420), and I've followed the steps, didn't help (e.g. remove `chroot` and restart);
* Some other threads found by googling keyword `UnsatisfiedLinkError` or `RunScriptNetHunter`, `com.offsec.nhterm.TermExec` didn't really help either.

Please help guide me how to troubleshoot this crash.  Thanks in advance.  Any help is greatly appreciated!

**Comment by Shuoen1997** [comment]
I'm experiencing the same issue too. Did you figure out any solution?

**Comment by amzker** [comment]
Reinstall And Solve

**Comment by thyrlian** [comment]
A while after no solution found, I flashed my Nexus 9 back with the official Android ROM.  But I'm gonna give a try again once back home from vacation, since my Nexus 9 is not with me at the moment.  @Shuoen1997 I guess you tried with the latest build?  When yes, I don't see any point that I should try again, as the result would be the same from my side (same hardware, same build of Kali).  @amzker would be great if you could explain more why reinstall could solve the problem and by which kind of reinstall (just install Kali -> crash -> reinstall Kali on top of the old Kali without clean it?).  Thanks in advance.

**Comment by amzker** [comment]
@thyrlian 
I say Reinstall Because I Also Suffered This Problem
I Am In S7 Edge LineageOS Andy 8.1.0
So I Downloaded Zip Of Nethunter marshmallow 
And Than I Extract Chroot

And Install It Via Nethunter Apk 
For You 

Flash TWRP Recovery 
And Flash Nethunter Zip As Your Nexus Phone 

No Data Erased So Dont Worry

**Comment by thyrlian** [comment]
Thanks @amzker, I'll give a try soon.
