### ISSUE TITLE
'msfdb init' Error Initializing Metasploit

### ISSUE THREAD

**Issue by prairie-guy** [offensive-security/kali-nethunter#465]
I am running nethunter on Nexus 6p with marshmallow and a kali-rollng distribution. Two days ago, I downloaded and rebuilt a customized nethunter image. Before initializing the Metasploit-framework, I did a system refresh with 'apt-get install && apt-get update'. I notice that Postgresql was updated during the process. (Framework: 4.12.4-dev and psql (PostgreSQL) 9.5.3)

Starting postgresql worked as expected:
service postgresql start

msfdb initialization started as expected, but then failed:
msfdb init

I am able to avoid the problem by using 'msfdb init' _before_ running 'apt-get install && apt-get upgrade'. 

Here is the output:

msfdb init

```
ArgumentError: undefined class/module PCAPRUB::LinkTypeError
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_suppor\
t/dependencies.rb:274:in
/`require'                                                                                          
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_suppor\
t/dependencies.rb:274:in                                                                            
/`block in require'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_suppor\
t/dependencies.rb:240:in
/`load_dependency'                                                                                  
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_suppor\
t/dependencies.rb:274:in                                                                            
/`require'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_suppor\
t/dependencies.rb:274:in
/`require'
. . .
/(required)>'                                                                                       
/usr/share/metasploit-framework/Rakefile:2:in `require'
/usr/share/metasploit-framework/Rakefile:2:in `<top (required)>'                                    
(See full trace by running task with --trace)
```

**Comment by pdxjohnny** [comment]
This happens to me as well and it happened after I ran the update + upgrade

**Comment by pdxjohnny** [comment]
```log
root@kali:~# msfdb reinit
Creating database user 'msf'
Enter password for new role: 
Enter it again: 
Creating databases 'msf' and 'msf_test'
Creating configuration file in /usr/share/metasploit-framework/config/database.yml
Creating initial database schema
rake aborted!
ArgumentError: undefined class/module PCAPRUB::LinkTypeError
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/usr/share/metasploit-framework/lib/metasploit/framework.rb:14:in `<top (required)>'
/usr/share/metasploit-framework/config/application.rb:10:in `<top (required)>'
/usr/share/metasploit-framework/Rakefile:2:in `require'
/usr/share/metasploit-framework/Rakefile:2:in `<top (required)>'
ArgumentError: undefined class/module PCAPRUB::LinkTypeError
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/usr/share/metasploit-framework/lib/metasploit/framework.rb:14:in `<top (required)>'
/usr/share/metasploit-framework/config/application.rb:10:in `<top (required)>'
/usr/share/metasploit-framework/Rakefile:2:in `require'
/usr/share/metasploit-framework/Rakefile:2:in `<top (required)>'
LoadError: cannot load such file -- metasploit-framework
/usr/share/metasploit-framework/config/application.rb:10:in `<top (required)>'
/usr/share/metasploit-framework/Rakefile:2:in `require'
/usr/share/metasploit-framework/Rakefile:2:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by vay3t** [comment]
I have the same problem, in  metasploit not work in the search command.``` [-] Error while running command search: ```

**Comment by pdxjohnny** [comment]
I just some more information, I have a fresh install all I have done is run the update and init then it didn't work because it complained about missing rake then I ran the update + upgrade and ran reinit

**Comment by prairie-guy** [comment]
Did that work? I installed an older (working) image of Nethunter, did init and then did update & upgrade. Will fix my personal install scripts to reflect your solution. Thanks.

**Comment by pdxjohnny** [comment]
I am having this problem on the basic desktop version

**Comment by pdxjohnny** [comment]
so this works on master (https://github.com/rapid7/metasploit-framework/commit/37efff59ce1eb42c3764398d030b1f7cb437aaa4) so im assuming this is a problem with the package in the kali repos

**Comment by isischan** [comment]
this happen to me right after apt-get update 

root@jinX:~# msfconsole
Could not find activesupport-4.2.6 in any of the sources
Run `bundle install` to install missing gems.
