### ISSUE TITLE
Terminal Closes (Possible Architecture Mismatch)

### ISSUE THREAD

**Issue by hackdefendr** [offensive-security/kali-nethunter#578]
### Device:
NEXUS 9

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
NOUGAT

### Built from repo (date and build command) or downloaded from website (links):
LATEST

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.10.101-ga139acc (android-build@vped14.mtv.corp.google.com) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #1 SMP PREEMPT Thu Jul 21 17:32:05 UTC 2016

## Issue:

I need ARM64 version of Nethunter Terminal, as I believe the application closing is due to an architecture mismatch.

**Comment by binkybear** [comment]
The terminal doesn't have issues with arm64.  First, does it close when if you run app and hit android button?  Usually an error is caused by:

- Missing chroot
- Missing busybox
- Missing supersu
- Missing bootkali

I have added checks in latest terminal for bootkali and chroot.  You can test all the things above by going into adb shell and typing:
```
su
bootkali
```
If that boots fine then there is possibly something wrong with latest app update.

**Comment by hackdefendr** [comment]
Thanks for the quick response.

All exist...chroot, busybox, supersu, and bootkali

```
root@kali:/# uname -a
Linux kali 3.10.101-ga139acc #1 SMP PREEMPT Thu Jul 21 17:32:05 UTC 2016 aarch64 GNU/Linux
```

```
root@kali:/# ls -a
.  ..  bin  boot  captures  dev  etc  external_sd  home  lib  media  mnt  opt  proc  root  run  sbin  sdcard  srv  sys  system  tmp  usr  var
```

**Comment by binkybear** [comment]
What happens when you run the terminal?  Can you give me a logcat?  Have you tried reinstalling with latest apk?

**Comment by hackdefendr** [comment]
Yes and Yes.

I have a logcat from running the latest NH apk and an NMAP against my firewall. Here comes the logcat snippet:

```
09-18 10:23:59.666  1273  1334 I WindowManager: Destroying surface Surface(name=Starting com.offsec.nethunter) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.destroyOrSaveSurface:2073 com.android.server.wm.AppWindowToken.destroySurfaces:363 com.android.server.wm.WindowStateAnimator.finishExit:565 com.android.server.wm.WindowStateAnimator.stepAnimationLocked:491 com.android.server.wm.WindowAnimator.updateWindowsLocked:303 com.android.server.wm.WindowAnimator.animateLocked:704
09-18 10:23:59.735  6294  6294 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
09-18 10:23:59.756  6294  6294 W main    : type=1400 audit(0.0:75): avc: denied { write } for name="arm64" dev="dm-0" ino=189 scontext=u:r:shell:s0 tcontext=u:object_r:dalvikcache_data_file:s0 tclass=dir permissive=0
09-18 10:23:59.759  6294  6294 W main    : type=1400 audit(0.0:76): avc: denied { write } for name="arm64" dev="dm-0" ino=189 scontext=u:r:shell:s0 tcontext=u:object_r:dalvikcache_data_file:s0 tclass=dir permissive=0
09-18 10:23:59.802  6294  6294 I Radio-JNI: register_android_hardware_Radio DONE
09-18 10:23:59.838  6294  6294 D AndroidRuntime: Calling main entry com.android.commands.am.Am
09-18 10:23:59.868  1273  1597 E ActivityManager: Sending non-protected broadcast eu.chainfire.supersu.NativeAccess from system uid 0 pkg null
09-18 10:23:59.868  1273  1597 E ActivityManager: java.lang.Throwable
09-18 10:23:59.868  1273  1597 E ActivityManager: 	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:17695)
09-18 10:23:59.868  1273  1597 E ActivityManager: 	at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:18256)
09-18 10:23:59.868  1273  1597 E ActivityManager: 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:499)
09-18 10:23:59.868  1273  1597 E ActivityManager: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2755)
09-18 10:23:59.868  1273  1597 E ActivityManager: 	at android.os.Binder.execTransact(Binder.java:565)
09-18 10:23:59.916  6294  6294 D AndroidRuntime: Shutting down VM
09-18 10:23:59.953  1805  6317 D DropBoxEntryAddedChimeraService: User is not opted-in to Usage & Diagnostics or Lockbox.
09-18 10:24:00.020  6247  6318 I OpenGLRenderer: Initialized EGL, version 1.4
09-18 10:24:00.020  6247  6318 D OpenGLRenderer: Swap behavior 2
09-18 10:24:02.491  1273  1334 I WindowManager: Destroying surface Surface(name=Toast) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.destroyOrSaveSurface:2073 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementInner:429 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop:232 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement:180 com.android.server.wm.WindowManagerService$H.handleMessage:8079 android.os.Handler.dispatchMessage:102
09-18 10:24:11.670  6269  6274 I art     : Do partial code cache collection, code=50KB, data=58KB
09-18 10:24:11.670  6269  6274 I art     : After code cache collection, code=49KB, data=58KB
09-18 10:24:11.670  6269  6274 I art     : Increasing code cache capacity to 256KB
09-18 10:24:12.714  1433  1433 I DownloadManagerWrapper: onReceive() : Charging = true
09-18 10:24:13.051  1273  1408 I WifiHAL : Got channel list with 11 channels
09-18 10:24:13.052  1273  1408 I WifiHAL : Got channel list with 9 channels
09-18 10:24:13.053  1273  1408 I WifiHAL : Got channel list with 13 channels
09-18 10:24:13.560  1433  1433 W InputMethodService: Window size has been changed. This may cause jankiness of resizing window: -1 -> -2
09-18 10:24:13.560  1433  1433 I ClearcutLoggerManager: onStartInput()
09-18 10:24:13.561  1433  1433 I LatinIme: initialize() : Language = en-US
09-18 10:24:13.565  1433  1433 I LatinIme: onActivate() : EditorInfo = Package = com.offsec.nethunter : Type = Text : Learning = Enable : Suggestion = Show : AutoCorrection = Enable : Microphone = Show
09-18 10:24:13.571  1433  1433 W InputConnectionWrapper: Fixing selection indices to 0, 0
09-18 10:24:13.634  1433  1433 I LatinMotionHandler: consumeEvent() : GestureTypingEnabled = true
09-18 10:24:13.755  1433  1433 I ClearcutLoggerManager: onConnected()
09-18 10:24:17.727  1433  1438 I art     : Do partial code cache collection, code=114KB, data=110KB
09-18 10:24:17.727  1433  1438 I art     : After code cache collection, code=113KB, data=109KB
09-18 10:24:17.728  1433  1438 I art     : Increasing code cache capacity to 512KB
09-18 10:24:21.815  6269  6269 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
09-18 10:24:21.815  6269  6269 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
09-18 10:24:24.548  1433  1433 I LatinMotionHandler: consumeEvent() : GestureTypingEnabled = true
09-18 10:24:30.787  6269  6269 D NMAP CMD OUTPUT: : nmap  10.71.1.1
09-18 10:24:30.789  1273  1597 I ActivityManager: START u0 {act=com.offsec.nhterm.RUN_SCRIPT_NH cat=[android.intent.category.DEFAULT] cmp=com.offsec.nhterm/.RunScriptNetHunter (has extras)} from uid 10090 on display 0
09-18 10:24:30.832  1273  2743 I ActivityManager: Start proc 6325:com.offsec.nhterm/u0a91 for activity com.offsec.nhterm/.RunScriptNetHunter
09-18 10:24:30.929  6325  6325 I art     : Starting a blocking GC AddRemoveAppImageSpace
09-18 10:24:31.035  6269  6300 D OpenGLRenderer: endAllActiveAnimators on 0x78fadf5400 (RippleDrawable) with handle 0x78fab81e00
09-18 10:24:31.125  6325  6325 D Term    : TermService started
09-18 10:24:31.127  6325  6325 I TermService: Activity called onBind()
09-18 10:24:31.182  6325  6325 I TermService: Activity binding to service
09-18 10:24:31.182  6325  6325 D RUN_SCRIPT_NH: CMD: nmap  10.71.1.1
09-18 10:24:31.202  6325  6340 I OpenGLRenderer: Initialized EGL, version 1.4
09-18 10:24:31.202  6325  6340 D OpenGLRenderer: Swap behavior 2
09-18 10:24:31.395  6325  6325 D initialCommand: nmap  10.71.1.1
09-18 10:24:31.416  6325  6325 D MM createTermSession: /su/bin/su -c /system/bin/bootkalicmd: nmap  10.71.1.1
09-18 10:24:31.430  6325  6325 D CS: shell: /su/bin/su -c /system/bin/bootkali
09-18 10:24:31.430  6325  6325 D CS parse: : /su/bin/su -c /system/bin/bootkali
09-18 10:24:31.433  6325  6325 W m.offsec.nhterm: type=1400 audit(0.0:77): avc: denied { read } for name="libjackpal-termexec2nhj1.so" dev="dm-0" ino=109261 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=0
09-18 10:24:31.438  6325  6325 D AndroidRuntime: Shutting down VM
09-18 10:24:31.439  6325  6325 E AndroidRuntime: FATAL EXCEPTION: main
09-18 10:24:31.439  6325  6325 E AndroidRuntime: Process: com.offsec.nhterm, PID: 6325
09-18 10:24:31.439  6325  6325 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/Term-nh.apk"],nativeLibraryDirectories=[/data/app-lib/Term-nh, /system/fake-libs, /data/app/Term-nh.apk!/lib/armeabi, /system/lib, /vendor/lib]]] couldn't find "libjackpal-termexec2nhj1.so"
09-18 10:24:31.439  6325  6325 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:972)
09-18 10:24:31.439  6325  6325 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1530)
09-18 10:24:31.439  6325  6325 E AndroidRuntime: 	at com.offsec.nhterm.TermExec.<clinit>(TermExec.java:22)
09-18 10:24:31.439  6325  6325 E AndroidRuntime: 	at com.offsec.nhterm.TermExec.createSubprocess(TermExec.java:105)
09-18 10:24:31.439  6325  6325 E AndroidRuntime: 	at com.offsec.nhterm.ShellTermSession.createSubprocess(ShellTermSession.java:163)
09-18 10:24:31.439  6325  6325 E AndroidRuntime: 	at com.offsec.nhterm.ShellTermSession.initializeSession(ShellTermSession.java:105)
09-18 10:24:31.439  6325  6325 E AndroidRuntime: 	at com.offsec.nhterm.ShellTermSession.<init>(ShellTermSession.java:60)
09-18 10:24:31.439  6325  6325 E AndroidRuntime: 	at com.offsec.nhterm.Term.createTermSession(Term.java:592)
09-18 10:24:31.439  6325  6325 E AndroidRuntime: 	at com.offsec.nhterm.RemoteInterface.openNewWindow(RemoteInterface.java:165)
09-18 10:24:31.439  6325  6325 E AndroidRuntime: 	at com.offsec.nhterm.RunScriptNetHunter.handleIntent(RunScriptNetHunter.java:61)
09-18 10:24:31.439  6325  6325 E AndroidRuntime: 	at com.offsec.nhterm.RemoteInterface$1.onServiceConnected(RemoteInterface.java:55)
09-18 10:24:31.439  6325  6325 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1465)
09-18 10:24:31.439  6325  6325 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1482)
09-18 10:24:31.439  6325  6325 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
09-18 10:24:31.439  6325  6325 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-18 10:24:31.439  6325  6325 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
09-18 10:24:31.439  6325  6325 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6077)
09-18 10:24:31.439  6325  6325 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-18 10:24:31.439  6325  6325 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
09-18 10:24:31.439  6325  6325 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
09-18 10:24:31.442  1273  1597 W ActivityManager:   Force finishing activity com.offsec.nhterm/.RunScriptNetHunter
09-18 10:24:31.446  1273  1597 W ActivityManager:   Force finishing activity com.offsec.nethunter/.AppNavHomeActivity
09-18 10:24:31.548  1273  4336 I OpenGLRenderer: Initialized EGL, version 1.4
09-18 10:24:31.551  1273  4336 D OpenGLRenderer: Swap behavior 2
09-18 10:24:31.564  1805  6347 D DropBoxEntryAddedChimeraService: User is not opted-in to Usage & Diagnostics or Lockbox.
09-18 10:24:31.623  1433  1433 I LatinIme: abortComposing()
09-18 10:24:31.633  1273  1301 I WindowManager: Destroying surface Surface(name=com.offsec.nethunter/com.offsec.nethunter.AppNavHomeActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2478 com.android.server.wm.WindowManagerService.removeWindowLocked:2436 com.android.server.wm.WindowManagerService.removeWindowLocked:2305 com.android.server.wm.WindowManagerService.removeWindow:2300 com.android.server.wm.Session.remove:193
09-18 10:24:31.637  6269  6269 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
09-18 10:24:31.637  6269  6269 W IInputConnectionWrapper: beginBatchEdit on inactive InputConnection
09-18 10:24:31.637  6269  6269 W IInputConnectionWrapper: getSelectedText on inactive InputConnection
09-18 10:24:31.638  6269  6269 W IInputConnectionWrapper: endBatchEdit on inactive InputConnection
09-18 10:24:31.638  6269  6269 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
09-18 10:24:31.639  6269  6269 W IInputConnectionWrapper: getTextAfterCursor on inactive InputConnection
09-18 10:24:31.641  1433  1433 I LatinIme: onDeactivate()
09-18 10:24:31.643  1433  1433 I ClearcutLoggerManager: onFinishInput()
09-18 10:24:31.648  1433  1433 W InputMethodService: Window size has been changed. This may cause jankiness of resizing window: -1 -> -2
09-18 10:24:31.649  6269  6269 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
09-18 10:24:31.935  1273  1334 I WindowManager: Destroying surface Surface(name=InputMethod) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.destroyOrSaveSurface:2073 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementInner:429 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop:232 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement:180 com.android.server.wm.WindowManagerService$H.handleMessage:8079 android.os.Handler.dispatchMessage:102
09-18 10:24:31.946  1273  1309 W ActivityManager: Activity pause timeout for ActivityRecord{210d9c5 u0 com.offsec.nhterm/.RunScriptNetHunter t32 f}
09-18 10:24:32.608  1273  1334 I WindowManager: Destroying surface Surface(name=Starting com.offsec.nhterm) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2478 com.android.server.wm.AppWindowToken.destroySurfaces:365 com.android.server.wm.WindowStateAnimator.finishExit:565 com.android.server.wm.AppWindowAnimator.stepAnimationLocked:427 com.android.server.wm.WindowAnimator.updateAppWindowsLocked:176
09-18 10:24:32.664  1273  1334 W WindowManager: Failed looking up window
09-18 10:24:32.664  1273  1334 W WindowManager: java.lang.IllegalArgumentException: Requested window android.view.ViewRootImpl$W@e01f840 does not exist
09-18 10:24:32.664  1273  1334 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9100)
09-18 10:24:32.664  1273  1334 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9091)
09-18 10:24:32.664  1273  1334 W WindowManager: 	at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2296)
09-18 10:24:32.664  1273  1334 W WindowManager: 	at com.android.server.wm.Session.remove(Session.java:193)
09-18 10:24:32.664  1273  1334 W WindowManager: 	at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3286)
09-18 10:24:32.664  1273  1334 W WindowManager: 	at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5881)
09-18 10:24:32.664  1273  1334 W WindowManager: 	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3622)
09-18 10:24:32.664  1273  1334 W WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-18 10:24:32.664  1273  1334 W WindowManager: 	at android.os.Looper.loop(Looper.java:154)
09-18 10:24:32.664  1273  1334 W WindowManager: 	at android.os.HandlerThread.run(HandlerThread.java:61)
09-18 10:24:32.664  1273  1334 W WindowManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
09-18 10:24:35.302  1273  1960 D DhcpClient: Unicasting DHCPREQUEST ciaddr=10.71.1.150 request=0.0.0.0 serverid=null to /10.71.1.1:67
09-18 10:24:35.311  1273  2078 D DhcpClient: Received packet: b4:ce:f6:09:f8:90 ACK: your new IP /10.71.1.150, netmask /255.255.255.0, gateways [/10.71.1.1] DNS servers: /8.8.8.8 , lease time 3600
09-18 10:24:35.312  1273  1960 D DhcpClient: Renewed lease: IP address 10.71.1.150/24 Gateway 10.71.1.1  DNS servers: [ 8.8.8.8 ] Domains hackdefendr.com DHCP server /10.71.1.1 Vendor info null lease 3600 seconds
09-18 10:24:35.327  1273  1960 D DhcpClient: Scheduling renewal in 1799s
09-18 10:24:35.327  1273  1960 D DhcpClient: Scheduling rebind in 3149s
09-18 10:24:35.327  1273  1960 D DhcpClient: Scheduling expiry in 3599s
09-18 10:24:36.720  1433  2093 I art     : Waiting for a blocking GC DisableMovingGc
09-18 10:24:36.720  1433  2093 I art     : Starting a blocking GC DisableMovingGc
09-18 10:24:41.684  1433  4474 I ClearcutLoggerManager: flushAndDisconnect()
09-18 10:24:41.793  1433  4474 I ClearcutLoggerManager: flushAndDisconnect() : Success = true : Time = 19
09-18 10:24:42.468  1273  1309 W ActivityManager: Activity destroy timeout for ActivityRecord{210d9c5 u0 com.offsec.nhterm/.RunScriptNetHunter t32 f}
09-18 10:24:42.476  1273  1309 I WindowManager: Destroying surface Surface(name=com.offsec.nhterm/com.offsec.nhterm.RunScriptNetHunter) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2478 com.android.server.wm.WindowManagerService.removeWindowLocked:2436 com.android.server.wm.WindowManagerService.removeWindowLocked:2305 com.android.server.wm.AppWindowToken.removeAllWindows:530 com.android.server.wm.AppWindowToken.removeAppFromTaskLocked:326
09-18 10:25:12.718  1433  1433 I DownloadManagerWrapper: onReceive() : Charging = true
09-18 10:25:40.760  1878  6350 I SubscribedFeeds: Received message
09-18 10:25:40.808  5041  6351 W Gmail   : Sync started for account: account:1810845716
09-18 10:25:40.811  5041  6351 I Gmail   : notifyAccountChanged
09-18 10:25:40.816  5041  6352 I Gmail   : getAccountsCursor
09-18 10:25:40.827  1787  1787 I Auth    : [AuthDelegateWrapper] Service intent: Intent { cmp=com.google.android.gms/.auth.account.authenticator.DefaultAuthDelegateService }.
09-18 10:25:40.859  5041  6351 I Gmail   : MainSyncRequestProto: lowestBkwdConvoId: 0, highestHandledServerOp: 6223736, normalSync: true
09-18 10:25:40.885  5041  6351 I DefaultRequestDirector: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request: The target server failed to respond
09-18 10:25:40.885  5041  6351 I DefaultRequestDirector: Retrying request
09-18 10:25:41.141  1787  3143 W Herrevad: Invalid mccmnc
09-18 10:25:41.144  1787  3143 W Herrevad: Invalid mccmnc
09-18 10:25:41.154  1787  1787 I Auth    : [AuthDelegateWrapper] Service intent: Intent { cmp=com.google.android.gms/.auth.account.authenticator.DefaultAuthDelegateService }.
09-18 10:25:41.255  5041  6351 I Gmail   : MainSyncRequestProto: lowestBkwdConvoId: 0, highestHandledServerOp: 6223819, normalSync: true
09-18 10:25:41.571  1787  3143 W Herrevad: Invalid mccmnc
09-18 10:25:41.577  1787  3143 W Herrevad: Invalid mccmnc
09-18 10:25:41.577  1787  1787 I Auth    : [AuthDelegateWrapper] Service intent: Intent { cmp=com.google.android.gms/.auth.account.authenticator.DefaultAuthDelegateService }.
09-18 10:25:41.681  5041  6351 I Gmail   : MainSyncRequestProto: lowestBkwdConvoId: 0, highestHandledServerOp: 6223819, normalSync: true
09-18 10:25:41.684  5041  6351 I Gmail   : lowestBackward conversation id 0
09-18 10:25:41.768  1805  6355 W IcingInternalCorpora: getNumBytesRead when not calculated.
09-18 10:25:41.775  5041  6351 I Gmail   : AppDataSearch: minSeqNo=300, maxSeqNo=394, lastCommittedSequence=360
09-18 10:25:41.837  1805  2046 I Icing   : Usage reports 2 indexed 0 rejected 0 imm upload false
09-18 10:25:41.861  5041  6351 I Gmail   : Sending provider changed intent: Intent { act=android.intent.action.PROVIDER_CHANGED dat=content://gmail-ls/unread/^sq_ig_i_group (has extras) }
09-18 10:25:41.883  5041  6351 I Gmail   : notifyAccountChanged
09-18 10:25:41.886  5041  6351 W Gmail   : Sync complete for account: account:1810845716
09-18 10:25:41.886  5041  6359 I Gmail   : getAccountsCursor
09-18 10:25:41.889  1787  1787 I Auth    : [AuthDelegateWrapper] Service intent: Intent { cmp=com.google.android.gms/.auth.account.authenticator.DefaultAuthDelegateService }.
09-18 10:25:42.882  1805  2046 I Icing   : Indexing BA39543DFBE9D6996E11B92DC2967B8234224EFD from com.google.android.gm
09-18 10:25:43.055  1805  2046 I Icing   : Indexing done BA39543DFBE9D6996E11B92DC2967B8234224EFD
```

**Comment by hackdefendr** [comment]
Is this the point of when the app closed?

`java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/Term-nh.apk"],nativeLibraryDirectories=[/data/app-lib/Term-nh, /system/fake-libs, /data/app/Term-nh.apk!/lib/armeabi, /system/lib, /vendor/lib]]] couldn't find "libjackpal-termexec2nhj1.so"`

**Comment by binkybear** [comment]
Here is the error:
```bash
09-18 10:24:31.433  6325  6325 W m.offsec.nhterm: type=1400 audit(0.0:77): avc: denied { read } for name="libjackpal-termexec2nhj1.so" dev="dm-0" ino=109261 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=0
09-18 10:24:31.438  6325  6325 D AndroidRuntime: Shutting down VM
09-18 10:24:31.439  6325  6325 E AndroidRuntime: FATAL EXCEPTION: main
09-18 10:24:31.439  6325  6325 E AndroidRuntime: Process: com.offsec.nhterm, PID: 6325
09-18 10:24:31.439  6325  6325 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/Term-nh.apk"],nativeLibraryDirectories=[/data/app-lib/Term-nh, /system/fake-libs, /data/app/Term-nh.apk!/lib/armeabi, /system/lib, /vendor/lib]]] couldn't find "libjackpal-termexec2nhj1.so"
09-18 10:24:31.439  6325  6325 E AndroidRuntime:    at java.lang.Runtime.loadLibrary0(Runtime.java:972)
09-18 10:24:31.439  6325  6325 E AndroidRuntime:    at java.lang.System.loadLibrary(System.java:1530)
09-18 10:24:31.439  6325  6325 E AndroidRuntime:    at com.offsec.nhterm.TermExec.<clinit>(TermExec.java:22)
09-18 10:24:31.439  6325  6325 E AndroidRuntime:    at com.offsec.nhterm.TermExec.createSubprocess(TermExec.java:105)
09-18 10:24:31.439  6325  6325 E AndroidRuntime:    at com.offsec.nhterm.ShellTermSession.createSubprocess(ShellTermSession.java:163)
09-18 10:24:31.439  6325  6325 E AndroidRuntime:    at com.offsec.nhterm.ShellTermSession.initializeSession(ShellTermSession.java:105)
09-18 10:24:31.439  6325  6325 E AndroidRuntime:    at com.offsec.nhterm.ShellTermSession.<init>(ShellTermSession.java:60)
09-18 10:24:31.439  6325  6325 E AndroidRuntime:    at com.offsec.nhterm.Term.createTermSession(Term.java:592)
09-18 10:24:31.439  6325  6325 E AndroidRuntime:    at com.offsec.nhterm.RemoteInterface.openNewWindow(RemoteInterface.java:165)
09-18 10:24:31.439  6325  6325 E AndroidRuntime:    at com.offsec.nhterm.RunScriptNetHunter.handleIntent(RunScriptNetHunter.java:61)
09-18 10:24:31.439  6325  6325 E AndroidRuntime:    at com.offsec.nhterm.RemoteInterface$1.onServiceConnected(RemoteInterface.java:55)
09-18 10:24:31.439  6325  6325 E AndroidRuntime:    at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1465)
09-18 10:24:31.439  6325  6325 E AndroidRuntime:    at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1482)
09-18 10:24:31.439  6325  6325 E AndroidRuntime:    at android.os.Handler.handleCallback(Handler.java:751)
09-18 10:24:31.439  6325  6325 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:95)
09-18 10:24:31.439  6325  6325 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:154)
09-18 10:24:31.439  6325  6325 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:6077)
09-18 10:24:31.439  6325  6325 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
09-18 10:24:31.439  6325  6325 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
09-18 10:24:31.439  6325  6325 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
09-18 10:24:31.442  1273  1597 W ActivityManager:   Force finishing activity com.offsec.nhterm/.RunScriptNetHunter
09-18 10:24:31.446  1273  1597 W ActivityManager:   Force finishing activity com.offsec.nethunter/.AppNavHomeActivity
09-18 10:24:31.548  1273  4336 I OpenGLRenderer: Initialized EGL, version 1.4
```
I would say first try seeing/checking that you have option to run untrusted app and selinux is set to permissive (su && setenforce 0).  I'll update this comment as I read through this more.

**Comment by hackdefendr** [comment]
No need....that bugger selinux was the culprit.

Did I miss this step? Or does it need to be added to 'setenforce 0' before running any NH apps?

**Comment by binkybear** [comment]
We usually have it run in bootkali script without any issues.  However, this seems to be an issue with application and selinux (not bootkali since that runs fine for you).  

I haven't been on Nougat yet so I get the feeling it might be a permissions issue somewhere.

**Comment by hackdefendr** [comment]
As a test...

I re-enabled it and tried the basic NH Terminal and tapped Kali. Instant close.

Disabled selinux again, and same test passes. If bootkali does this, then its not sticking for some reason and causing the app to close.

**Comment by binkybear** [comment]
The issue is that app is running before bootkali.  The app is getting denied before bootkali has a chance to run setenforce 0. * I think

**Comment by hackdefendr** [comment]
Again thanks for the quickness. This was probably an easy one for you, but still, thanks.

**Comment by SecurityAddicted** [comment]
I can confirm this issue is still present on the latest nightly for Nougat & Nexus 9.
1. Terminal force close (getenforce == Enforcing)
2. run setenforce 0 (getenforce == Permissive)
3. Terminal run fine
I'm on Android 7.1.1
Nethunter version 3.15.3-20161222-1600
